[package]
name = "project_euler_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true

[dependencies]
chrono = "0.4.41"
num-bigint = "0.4.6"
num-iter = "0.1.45"
